services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
  worker:
    build:
      context: ./backend
    command: celery -A worker.tasks:celery_app worker
    environment:
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
      - "5678:5678" # debugpy
    volumes:
      - ./backend:/app
    command: >
      bash -c "alembic upgrade head && python -Xfrozen_modules=off -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DEBUGPY: "1"
      DEBUGPY_PORT: "5678"
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  scheduler:
    build:
      context: ./backend/scheduler
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./backend/scheduler:/app
    command: go run scheduler.go
  frontend:
    build:
      context: ./frontend
      # Use the final stage image; we'll install dev deps at runtime
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NODE_ENV: development
    command: pnpm run dev
volumes:
  db_data:
