version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  scheduler:
    build:
      context: ./backend
      dockerfile: scheduler/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    command: go run scheduler.go

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    command: npm run build && npm start
