services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ajwong
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: job_apps
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  scheduler:
    build:
      context: ./backend/scheduler
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./backend/scheduler:/app
    command: go run scheduler.go
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev
volumes:
  db_data:
