"""update

Revision ID: 894818daa63f
Revises: 31371488829d
Create Date: 2025-09-09 14:44:22.036929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894818daa63f'
down_revision: Union[str, Sequence[str], None] = '31371488829d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assessment', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('interview', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview')
    op.drop_column('applications', 'assessment')
    # ### end Alembic commands ###
