"""make claims non nullable

Revision ID: d47fc60ea65f
Revises: d5d3dc44946d
Create Date: 2025-09-18 02:54:44.191236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47fc60ea65f'
down_revision: Union[str, Sequence[str], None] = 'd5d3dc44946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'prepare_claim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'submission_claim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'review_claim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'create_app_claim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'expiration_check_claim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'expiration_check_claim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'create_app_claim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'review_claim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'submission_claim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'prepare_claim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
