"""update

Revision ID: fee4372b6d1f
Revises: 7d53e04d117f
Create Date: 2025-08-26 19:45:57.140255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee4372b6d1f'
down_revision: Union[str, Sequence[str], None] = '7d53e04d117f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
