"""update

Revision ID: 2bd9fa7ff371
Revises: fee4372b6d1f
Create Date: 2025-08-27 23:19:28.006656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd9fa7ff371'
down_revision: Union[str, Sequence[str], None] = 'fee4372b6d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('discarded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'discarded')
    # ### end Alembic commands ###
