"""update

Revision ID: 31371488829d
Revises: 839479daf8f5
Create Date: 2025-09-09 14:13:17.873662

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31371488829d'
down_revision: Union[str, Sequence[str], None] = '839479daf8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'manual')
    op.add_column('jobs', sa.Column('manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'manual')
    op.add_column('applications', sa.Column('manual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
