"""removed form foreign key from ApplicationORM

Revision ID: 65cabdfea9ca
Revises: 4bcd95243d53
Create Date: 2025-09-25 02:29:59.057213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cabdfea9ca'
down_revision: Union[str, Sequence[str], None] = '4bcd95243d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_form_id_fkey'), 'applications', type_='foreignkey')
    op.drop_column('applications', 'form_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('form_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('applications_form_id_fkey'), 'applications', 'application_forms', ['form_id'], ['id'])
    # ### end Alembic commands ###
