"""update

Revision ID: 839479daf8f5
Revises: ac5cd6f003c3
Create Date: 2025-09-09 14:10:08.928226

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '839479daf8f5'
down_revision: Union[str, Sequence[str], None] = 'ac5cd6f003c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'manual')
    # ### end Alembic commands ###
