"""update

Revision ID: 8fa3b08c7b29
Revises: 492998d32864
Create Date: 2025-08-29 03:07:38.171773

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8fa3b08c7b29'
down_revision: Union[str, Sequence[str], None] = '492998d32864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
