"""update

Revision ID: ac5cd6f003c3
Revises: fccede04ce80
Create Date: 2025-09-02 22:58:38.445127

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac5cd6f003c3'
down_revision: Union[str, Sequence[str], None] = 'fccede04ce80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('approved', sa.Boolean(), nullable=True))
    op.drop_column('applications', 'user_approved')
    op.add_column('jobs', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('discarded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'discarded')
    op.drop_column('jobs', 'approved')
    op.add_column('applications', sa.Column('user_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'approved')
    # ### end Alembic commands ###
