"""update

Revision ID: ceb06033ceb9
Revises: cb9514f1c322
Create Date: 2025-09-15 13:05:10.086809

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ceb06033ceb9'
down_revision: Union[str, Sequence[str], None] = 'cb9514f1c322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('expired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'expired')
    # ### end Alembic commands ###
