"""added claims

Revision ID: d5d3dc44946d
Revises: ceb06033ceb9
Create Date: 2025-09-18 02:49:33.177694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d3dc44946d'
down_revision: Union[str, Sequence[str], None] = 'ceb06033ceb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('prepare_claim', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('submission_claim', sa.Boolean(), nullable=True))
    op.alter_column('applications', 'prepared',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'discarded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'referred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'submitted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'assessment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'interview',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'rejected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('applications', 'scraped')
    op.alter_column('errors', 'error_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('errors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('jobs', sa.Column('review_claim', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('create_app_claim', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('expiration_check_claim', sa.Boolean(), nullable=True))
    op.alter_column('jobs', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'discarded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'manual',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'expired',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'expired',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'manual',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'discarded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('jobs', 'expiration_check_claim')
    op.drop_column('jobs', 'create_app_claim')
    op.drop_column('jobs', 'review_claim')
    op.alter_column('errors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('errors', 'error_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('applications', sa.Column('scraped', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'rejected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'interview',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'assessment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'submitted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'referred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'discarded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applications', 'prepared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('applications', 'submission_claim')
    op.drop_column('applications', 'prepare_claim')
    # ### end Alembic commands ###
